spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
  profiles:
    include: oauth

server:
  servlet:
    encoding:
      force-response: true